### ISSUE TITLE
The Font Won't Change to Custom Handwriting

### ISSUE THREAD

**Issue by karanshah0206** [karanshah0206/Type-To-Write#7]
![IMG-20200414-WA0057](https://user-images.githubusercontent.com/62107454/79259643-aa01b480-7eaa-11ea-9660-26a3c3cbb8e1.jpg)

When a personalized font is uploaded, it shows in the preview, but not in the final scan copy.

**Comment by krrysis** [comment]
I saw the code, I think the issue exists because during generating the op, you're using the default cursive font, instead of the uploaded font.
`function applyPaperStyles() {
  textareaEl.style.fontFamily = document.getElementById("handwriting-font").value;`
I guess here you'll need to create a if condition to see if there is an file uploaded, if yes then take the new fon't in textareaEl.style.fontFamily instead of the default one.

**Comment by karanshah0206** [comment]
Yes, I saw that. I modified that. However, I realized that the domtoimage library that I am using does not support externally uploaded files, sadly. Therefore, I am trying to integrate another library. However, thank you very much for the help!

**Comment by krrysis** [comment]
I have a doubt, how have you integrated the 3 existing fonts with the project? is there a way to change some part of the code to integrate our font?

**Comment by karanshah0206** [comment]
The integration of the three default fonts:
`<link href="https://fonts.googleapis.com/css?family=Caveat|Homemade+Apple|Liu+Jian+Mao+Cao&display=swap" rel="stylesheet" crossorigin="anonymous">`

I think we can try to upload the custom font on a cloud service such as Microsoft OneDrive and link that into the code. Maybe I should give that a shot for the sake of experiment. However, uploading to cloud each time a user uploads a new font doesn't seem like a practical idea to me from a end-product perspective. Regardless, it's neat for the sake of experiment and we can give it a shot!

**Comment by krrysis** [comment]
let me try it if I can do it, while you try it too at your end, also if it works we can create something that will be user friendly.

**Comment by krrysis** [comment]
![image](https://user-images.githubusercontent.com/8746269/79352009-f0ace880-7f56-11ea-88fa-d4ca65ee750c.png)
were you successful in your attempt? even though I tried creating my custom font and tweaking the code a little, it won't load my fonts, it's loading some font that looks like above where as my custom fonts look like this.
![image](https://user-images.githubusercontent.com/8746269/79352186-25b93b00-7f57-11ea-96c7-de3c1623c519.png)

I had uploaded my custom fonts on https://fonts-two.now.sh/Krrysis-Regular.ttf
and replaced `<link href="https://fonts.googleapis.com/css?family=Caveat|Homemade+Apple|Liu+Jian+Mao+Cao&display=swap" rel="stylesheet" crossorigin="anonymous">` with my own file at https://fonts-two.now.sh/font.css

**Comment by karanshah0206** [comment]
![Screenshot (83)](https://user-images.githubusercontent.com/62107454/79352861-fd7e0c00-7f57-11ea-9855-7814203c04de.png)
For me it's simply denying the existence of any new font and going into this random, ig default font that Microsoft Edge uses if there is no predefined font. For some reason, I used the same link code that you used, yet it isn't allowing me font edits.

**Comment by krrysis** [comment]
the file I've uploaded at https://fonts-two.now.sh/font.css if I replace it in your original code files. So we can eliminate that as the issue. Secondly yes, I guess those are default edge fonts. But idk why am I getting **Comic Sans MS** fonts. I've no where mentioned in the code to use that font, as a matter of fact I replaced _homemade apple_ with _krrysis_ everywhere. there is no single mention of comic sans nor does my system/edge uses this font. This makes it especially confusing
--update--
Ig the issue could be with extension. Rest other font files by font.googleapis use woff2 extension and mine uses ttf. still I'm not sure. I'll try converting ttf to woff2
--update2--
No difference, I'll try to use everything locally

**Comment by karanshah0206** [comment]
> Ig the issue could be with extension
I initially thought that this was something to do with the image library as well. However, what bugs me is that if I directly link a Google API font, it works. But when I upload the same font from my computer, it won't work. Therefore, I think the DOM-to-image library is working, and there is some problem with the readFile function that reads the uploaded TTF. I think we should try and modify that one.

**Comment by krrysis** [comment]
No i don't think it has anything to do with Readfile function. I'm doing everything locally, I'm not uploading any fonts or selecting any new fonts. What I'm doing right is replacing existing fonts with my new fonts and it works perfectly, the only issue is with the generated image. left side stays my custom font, the generated image is comic sans ms. I'm not even touching the readfile function.
--update--
the entire webpage uses my custom fonts if I wish to, but the generated image won't use it, sure something must be of an issue in the library.

**Comment by karanshah0206** [comment]
Yeah, maybe it's the library after all. I tried understanding the library but it's too complicated and editing one element ruins many others because the library is too interconnected in terms of variables and parameters. So maybe we should find a better library. I tried 2, but both ruin many of the other elements of this site. We both can search neat image mod libraries and test. If we find a good one, we'll implement. What say?

**Comment by krrysis** [comment]
Okay i saw the library it says only WOFF and EOF fonts are acceptable, whereas we are using WOFF2, just let me once try using WOFF. I'll update this comment for updates.
--update--
same results with ttf, woff, woff2, eot.

>  We both can search neat image mod libraries and test. If we find a good one, we'll implement. > >  What say?

there are couple of libraries out there, but they are not single file libraries like cdnjs library you used. So will have to integrate it somehow. 

meanwhile try opening a thread on Stackoverflow

https://youtu.be/lYrjK5fH-1g 
check this video, I'm neither using Arial font nor using comic sans, but still the dom to image library updates fonts so maybe we are missing something in the implementation part and nothings wrong with the library.

also at the same time something seems definitely wrong with the library, keeping text area aside I can easily change website fonts to custom fonts but If i use the same library to take the screenshot of entire body then i get the screenshot but not in the changed fonts but normal fonts

website:
![image](https://user-images.githubusercontent.com/8746269/79382070-93c62800-7f80-11ea-968f-3dc35d0a98c3.png)

screenshot with library
![image](https://user-images.githubusercontent.com/8746269/79382108-a3457100-7f80-11ea-9b74-9d95a6f30107.png)

**Comment by karanshah0206** [comment]
I'm not to sure that the error would be caused because the font is woff2, because the default fonts were also in woff2 format, yet they're running prefectly.

It's weird why you can't get the screen shot done, because my screen shots can be taken without any problem.

**Comment by krrysis** [comment]
No, I can take screenshots perfectly, I'm saying that it just won't take a screenshot with the same fonts. And I followed some issues of the github repo of the library, the problem lies with library itself. Multiple issues of the same has been raised.

https://github.com/tsayen/dom-to-image/issues/45#issue-163512082

https://github.com/tsayen/dom-to-image/issues/279

**Comment by karanshah0206** [comment]
The font issue was fixed. The DOM-To-Image Library was replaced by HTML2Canvas Library. It appears that the former library was unable to read externally linked CSS rulesheets and only worked with rulesheets that were directly a part of the website folder. The new library is fully compatible with externally linked rulesheets.

![Screenshot (86)](https://user-images.githubusercontent.com/62107454/79571626-1e219f80-80d9-11ea-861c-bfbaa1aa665b.png)

**Comment by krrysis** [comment]
Great work with the new library. Works perfectly.

**Comment by krishnnnnaaa** [comment]
It's working perfectly but there are some issues in this lib also, like I'm unable to add box shadow property.
